DEVICE_FIRMWARE_URLS = {
    "FP3": [
        {"name": "boot.img", "url": "https://gitlab.com/ubports/porting/community-ports/android10/fairphone/fairphone_fp3/-/jobs/2902188165/artifacts/raw/out/boot.img", "size": 0},
    ],
    "FP4": [
        {"name": "boot.img", "url": "https://cdimage.ubports.com/devices/FP4/boot.img", "size": 0},
        {"name": "dtbo.img", "url": "https://cdimage.ubports.com/devices/FP4/dtbo.img", "size": 0},
        {"name": "recovery.img", "url": "https://cdimage.ubports.com/devices/FP4/recovery.img", "size": 0},
    ],
    "FP5": [
        {"name": "boot.img", "url": "https://cdimage.ubports.com/devices/FP5/boot.img", "size": 0},
        {"name": "vendor_boot.img", "url": "https://cdimage.ubports.com/devices/FP5/vendor_boot.img", "size": 0},
    ],
    "Spacewar": [
        {"name": "boot.img", "url": "https://github.com/Nonta72/nothing-spacewar/releases/download/UT-24.02_v12/boot.img", "size": 0},
        {"name": "vendor_boot.img", "url": "https://github.com/Nonta72/nothing-spacewar/releases/download/UT-24.02_v12/vendor_boot.img", "size": 0},
    ],
    "X00TD": [
        {"name": "vendor_X00TD.zip", "url": "https://github.com/Linux-On-Sdm6Series/android/releases/download/13-09-2021/vendor_X00TD.zip", "size": 0},
        {"name": "recovery_X00TD.img", "url": "https://github.com/Linux-On-Sdm6Series/android/releases/download/26-10-2021/recovery_X00TD.img", "size": 0},
        {"name": "firmware_X00TD.zip", "url": "https://github.com/Linux-On-Sdm6Series/android/releases/download/13-09-2021/firmware_X00TD.zip", "size": 0},
    ],
    "X605": [
        {"name": "boot.img", "url": "https://gitlab.com/ubports/porting/community-ports/android9/lenovo-tab-m10-fhd/lenovo-x605/-/jobs/6057055401/artifacts/raw/out/boot.img", "size": 0},
        {"name": "recovery.img", "url": "https://gitlab.com/ubports/porting/community-ports/android9/lenovo-tab-m10-fhd/lenovo-x605-assets/-/raw/main/recovery.img", "size": 0},
    ],
    "algiz": [
        {"name": "volla-algiz-13.0-ubports-installer-bootstrap.zip", "url": "https://volla.tech/filedump/volla-algiz-13.0-ubports-installer-bootstrap.zip", "size": 0},
        {"name": "volla-14.0-20241124-stable-BOOTSTRAP-algiz.zip", "url": "https://volla.tech/filedump/vollaos/volla-14.0-20241124-stable-BOOTSTRAP-algiz.zip", "size": 0},
    ],
    "amar_row_lte": [
        {"name": "boot.img", "url": "https://github.com/rubencarneiro/amar_row_lte/releases/download/1.0/boot.img", "size": 0},
        {"name": "recovery.img", "url": "https://github.com/rubencarneiro/amar_row_lte/releases/download/1.0/recovery.img", "size": 0},
        {"name": "dtbo.img", "url": "https://github.com/rubencarneiro/amar_row_lte/releases/download/1.0/dtbo.img", "size": 0},
        {"name": "vbmeta.img", "url": "https://github.com/rubencarneiro/amar_row_lte/releases/download/1.0/vbmeta.img", "size": 0},
    ],
    "amar_row_wifi": [
        {"name": "boot.img", "url": "https://github.com/rubencarneiro/amar_row_wifi/releases/download/1.0/boot.img", "size": 0},
        {"name": "recovery.img", "url": "https://github.com/rubencarneiro/amar_row_wifi/releases/download/1.0/recovery.img", "size": 0},
        {"name": "dtbo.img", "url": "https://github.com/rubencarneiro/amar_row_wifi/releases/download/1.0/dtbo.img", "size": 0},
        {"name": "vbmeta.img", "url": "https://github.com/rubencarneiro/amar_row_wifi/releases/download/1.0/vbmeta.img", "size": 0},
    ],
    "begonia": [
        {"name": "fw_begonia_V12.0.8.0.zip", "url": "https://github.com/ubuntu-touch-begonia/ubuntu-touch-begonia/releases/download/20210810/fw_begonia_V12.0.8.0.zip", "size": 0},
        {"name": "vendor.zip", "url": "https://github.com/ubuntu-touch-begonia/ubuntu-touch-begonia/releases/download/20210810/vendor.zip", "size": 0},
        {"name": "dtbo.img", "url": "https://github.com/ubuntu-touch-begonia/ubuntu-touch-begonia/releases/download/20210810/dtbo.img", "size": 0},
        {"name": "recovery.img", "url": "https://github.com/ubuntu-touch-begonia/ubuntu-touch-begonia/releases/download/20210810/recovery.img", "size": 0},
        {"name": "vbmeta.img", "url": "https://github.com/ubuntu-touch-begonia/ubuntu-touch-begonia/releases/download/20210810/vbmeta.img", "size": 0},
    ],
    "billie": [
        {"name": "boot.img", "url": "https://github.com/rubencarneiro/billie/releases/download/1.0/boot.img", "size": 0},
        {"name": "recovery.img", "url": "https://github.com/rubencarneiro/billie/releases/download/1.0/recovery.img", "size": 0},
        {"name": "persist.img", "url": "https://github.com/rubencarneiro/billie/releases/download/1.0/persist.img", "size": 0},
        {"name": "dtbo.img", "url": "https://github.com/rubencarneiro/billie/releases/download/1.0/dtbo.img", "size": 0},
        {"name": "vbmeta.img", "url": "https://github.com/rubencarneiro/billie/releases/download/1.0/vbmeta.img", "size": 0},
    ],
    "billie2": [
        {"name": "boot.img", "url": "https://github.com/rubencarneiro/billie2/releases/download/1.0/boot.img", "size": 0},
        {"name": "recovery.img", "url": "https://github.com/rubencarneiro/billie2/releases/download/1.0/recovery.img", "size": 0},
        {"name": "dtbo.img", "url": "https://github.com/rubencarneiro/billie2/releases/download/1.0/dtbo.img", "size": 0},
        {"name": "vbmeta.img", "url": "https://github.com/rubencarneiro/billie2/releases/download/1.0/vbmeta.img", "size": 0},
    ],
    "cheeseburger": [
        {"name": "halium-unlocked-recovery_cheeseburger.img", "url": "https://cdimage.ubports.com/devices/dumpling_cheeseburger/halium-unlocked-recovery_cheeseburger.img", "size": 0},
    ],
    "citrus": [
        {"name": "recovery.img", "url": "https://github.com/ubuntu-touch-juice/ubuntu-touch-citrus/releases/download/20210929/recovery.img", "size": 0},
        {"name": "dtbo.img", "url": "https://github.com/ubuntu-touch-juice/ubuntu-touch-citrus/releases/download/20210929/dtbo.img", "size": 0},
        {"name": "super.zip", "url": "https://github.com/ubuntu-touch-juice/ubuntu-touch-citrus/releases/download/20210929/super.zip", "size": 0},
        {"name": "vbmeta.img", "url": "https://dl.google.com/developers/android/qt/images/gsi/vbmeta.img", "size": 0},
    ],
    "denniz": [
        {"name": "super.zip", "url": "https://github.com/ubuntu-touch-denniz/ubuntu-touch-denniz/releases/download/20221020/super.zip", "size": 0},
        {"name": "recovery.img", "url": "https://github.com/ubuntu-touch-denniz/ubuntu-touch-denniz/releases/download/20221020/recovery.img", "size": 0},
        {"name": "dtbo.img", "url": "https://github.com/ubuntu-touch-denniz/ubuntu-touch-denniz/releases/download/20221020/dtbo.img", "size": 0},
        {"name": "vbmeta.img", "url": "https://dl.google.com/developers/android/qt/images/gsi/vbmeta.img", "size": 0},
    ],
    "dumpling": [
        {"name": "halium-unlocked-recovery_dumpling.img", "url": "https://cdimage.ubports.com/devices/dumpling_cheeseburger/halium-unlocked-recovery_dumpling.img", "size": 0},
    ],
    "enchilada": [
        {"name": "boot.img", "url": "https://cdimage.ubports.com/devices/enchilada_fajita/boot.img", "size": 0},
        {"name": "vbmeta.img", "url": "https://cdimage.ubports.com/devices/enchilada_fajita/vbmeta.img", "size": 0},
    ],
    "hero2lte": [
        {"name": "recovery_hero2lte.img", "url": "https://github.com/Kethen/samsung-exynos8890/releases/download/2022-07-23/recovery_hero2lte.img", "size": 0},
        {"name": "boot-reboot-recovery-hero2lte.img", "url": "https://github.com/Kethen/samsung-exynos8890/releases/download/2022-07-23/boot-reboot-recovery-hero2lte.img", "size": 0},
    ],
    "herolte": [
        {"name": "recovery_herolte.img", "url": "https://github.com/Kethen/samsung-exynos8890/releases/download/2022-07-23/recovery_herolte.img", "size": 0},
        {"name": "boot-reboot-recovery-herolte.img", "url": "https://github.com/Kethen/samsung-exynos8890/releases/download/2022-07-23/boot-reboot-recovery-herolte.img", "size": 0},
    ],
    "jasmine_sprout": [
        {"name": "boot.img", "url": "https://github.com/ubports-xiaomi-sdm660/artifacts/releases/download/v0.1/boot.img", "size": 0},
    ],
    "jingpad_a1": [
        {"name": "recovery.img", "url": "https://cdimage.ubports.com/devices/jingpad_a1/recovery.img", "size": 0},
        {"name": "vendor.img", "url": "https://cdimage.ubports.com/devices/jingpad_a1/vendor.img", "size": 0},
    ],
    "lancelot": [
        {"name": "recovery.img", "url": "https://github.com/ubuntu-touch-redmi-mt6768/lancelotfw/releases/download/20250217/recovery.img", "size": 0},
        {"name": "dtbo.img", "url": "https://github.com/ubuntu-touch-redmi-mt6768/lancelotfw/releases/download/20250217/dtbo.img", "size": 0},
        {"name": "super.zip", "url": "https://github.com/ubuntu-touch-redmi-mt6768/lancelotfw/releases/download/20250217/super.zip", "size": 0},
        {"name": "vbmeta.img", "url": "https://dl.google.com/developers/android/qt/images/gsi/vbmeta.img", "size": 0},
    ],
    "lavender": [
        {"name": "dtbo.img", "url": "https://cdimage.ubports.com/devices/lavender/dtbo.img", "size": 0},
        {"name": "recovery.img", "url": "https://cdimage.ubports.com/devices/lavender/recovery.img", "size": 0},
        {"name": "splash.img", "url": "https://cdimage.ubports.com/devices/lavender/splash.img", "size": 0},
        {"name": "vbmeta.img", "url": "https://cdimage.ubports.com/devices/lavender/vbmeta.img", "size": 0},
        {"name": "image-fastboot-lavender.zip", "url": "https://images.droidian.org/droidian/nightly/arm64/xiaomi/image-fastboot-lavender.zip", "size": 0},
        {"name": "droidian-OFFICIAL_xiaomi_lavender-arm64-cutie-phone-28.zip", "url": "https://github.com/cutie-shell/droidian/releases/download/nightly/droidian-OFFICIAL_xiaomi_lavender-arm64-cutie-phone-28.zip", "size": 0},
    ],
    "merlin": [
        {"name": "recovery.img", "url": "https://github.com/ubuntu-touch-redmi-mt6768/ubuntu-touch-merlin/releases/download/20250217/recovery.img", "size": 0},
        {"name": "dtbo.img", "url": "https://github.com/ubuntu-touch-redmi-mt6768/ubuntu-touch-merlin/releases/download/20250217/dtbo.img", "size": 0},
        {"name": "super.zip", "url": "https://github.com/ubuntu-touch-redmi-mt6768/ubuntu-touch-merlin/releases/download/20250217/super.zip", "size": 0},
        {"name": "vbmeta.img", "url": "https://dl.google.com/developers/android/qt/images/gsi/vbmeta.img", "size": 0},
    ],
    "miatoll": [
        {"name": "recovery.img", "url": "https://github.com/ubuntu-touch-miatoll/ubuntu-touch-miatoll/releases/download/stable-installer-fix/recovery.img", "size": 0},
        {"name": "dtbo.img", "url": "https://github.com/ubuntu-touch-miatoll/ubuntu-touch-miatoll/releases/download/stable-installer-fix/dtbo.img", "size": 0},
        {"name": "image-fastboot-miatoll.zip", "url": "https://images.droidian.org/droidian/nightly/arm64/xiaomi/image-fastboot-miatoll.zip", "size": 0},
        {"name": "droidian-OFFICIAL_xiaomi_miatoll-arm64-cutie-phone-29.zip", "url": "https://github.com/cutie-shell/droidian/releases/download/nightly/droidian-OFFICIAL_xiaomi_miatoll-arm64-cutie-phone-29.zip", "size": 0},
    ],
    "mimameid": [
        {"name": "volla-mimameid-11.0-ubports-installer-bootstrap-v3.zip", "url": "https://volla.tech/filedump/volla-mimameid-11.0-ubports-installer-bootstrap-v3.zip", "size": 0},
        {"name": "volla-12.1-20240228-stable-BOOTSTRAP-mimameid.zip", "url": "https://volla.tech/filedump/vollaos/volla-12.1-20240228-stable-BOOTSTRAP-mimameid.zip", "size": 0},
        {"name": "volla-mimameid-12.0-ubports-installer-bootstrap.zip", "url": "https://volla.tech/filedump/volla-mimameid-12.0-ubports-installer-bootstrap.zip", "size": 0},
        {"name": "twrp-mimameid.img", "url": "https://deb.cutie-shell.org/twrp-mimameid.img", "size": 0},
        {"name": "image-fastboot-mimameid.zip", "url": "https://images.droidian.org/droidian/nightly/arm64/volla/image-fastboot-mimameid.zip", "size": 0},
        {"name": "droidian-OFFICIAL_volla_mimameid-arm64-cutie-phone-30.zip", "url": "https://github.com/cutie-shell/droidian/releases/download/nightly/droidian-OFFICIAL_volla_mimameid-arm64-cutie-phone-30.zip", "size": 0},
    ],
    "mimameid_h12": [
        {"name": "volla-mimameid-12.0-ubports-installer-bootstrap.zip", "url": "https://volla.tech/filedump/volla-mimameid-12.0-ubports-installer-bootstrap.zip", "size": 0},
        {"name": "volla-12.1-20240228-stable-BOOTSTRAP-mimameid.zip", "url": "https://volla.tech/filedump/vollaos/volla-12.1-20240228-stable-BOOTSTRAP-mimameid.zip", "size": 0},
    ],
    "mimir": [
        {"name": "volla-mimir-13.0-ubports-installer-bootstrap.zip", "url": "https://volla.tech/filedump/volla-mimir-13.0-ubports-installer-bootstrap.zip", "size": 0},
        {"name": "volla-14.0-20250130-stable-BOOTSTRAP-mimir.zip", "url": "https://volla.tech/filedump/vollaos/volla-14.0-20250130-stable-BOOTSTRAP-mimir.zip", "size": 0},
    ],
    "pro1x": [
        {"name": "recovery.img", "url": "https://cdimage.ubports.com/devices/pro1x/recovery.img", "size": 0},
    ],
    "r1": [
        {"name": "super.zip", "url": "https://github.com/MinatiScape/ubtouch-on-r1/releases/download/v0.2/super.zip", "size": 0},
        {"name": "boot.img", "url": "https://github.com/MinatiScape/ubtouch-on-r1/releases/download/v0.2/boot.img", "size": 0},
        {"name": "vbmeta.img", "url": "https://dl.google.com/developers/android/qt/images/gsi/vbmeta.img", "size": 0},
    ],
    "sagit": [
        {"name": "vendor.zip", "url": "https://github.com/UbuntuTouch-sagit/ubuntu-touch-sagit/releases/download/v1.1/vendor.zip", "size": 0},
        {"name": "recovery.img", "url": "https://github.com/UbuntuTouch-sagit/ubuntu-touch-sagit/releases/download/v1.1/recovery.img", "size": 0},
    ],
    "sargo": [
        {"name": "boot.img", "url": "https://cdimage.ubports.com/devices/sargo/boot.img", "size": 0},
        {"name": "dtbo.img", "url": "https://cdimage.ubports.com/devices/sargo/dtbo.img", "size": 0},
        {"name": "vbmeta.img", "url": "https://cdimage.ubports.com/devices/sargo/vbmeta.img", "size": 0},
        {"name": "image-fastboot-sargo.zip", "url": "https://images.droidian.org/droidian/nightly/arm64/google/image-fastboot-sargo.zip", "size": 0},
        {"name": "droidian-OFFICIAL_google_sargo-arm64-cutie-phone-28.zip", "url": "https://github.com/cutie-shell/droidian/releases/download/nightly/droidian-OFFICIAL_google_sargo-arm64-cutie-phone-28.zip", "size": 0},
    ],
    "surya": [
        {"name": "recovery.img", "url": "https://github.com/ubuntu-touch-surya/ubuntu-touch-surya/releases/download/stable-repartition/recovery.img", "size": 0},
        {"name": "dtbo.img", "url": "https://github.com/ubuntu-touch-surya/ubuntu-touch-surya/releases/download/stable-repartition/dtbo.img", "size": 0},
        {"name": "super.img", "url": "https://github.com/ubuntu-touch-surya/ubuntu-touch-surya/releases/download/stable-repartition/super.img", "size": 0},
        {"name": "vendor.img", "url": "https://github.com/ubuntu-touch-surya/ubuntu-touch-surya/releases/download/stable-repartition/vendor.img", "size": 0},
    ],
    "vidofnir_esim": [
        {"name": "volla-vidofnir-12.0-ubports-installer-bootstrap-v3.zip", "url": "https://volla.tech/filedump/volla-vidofnir-12.0-ubports-installer-bootstrap-v3.zip", "size": 0},
        {"name": "volla-14.0-20250128-stable-BOOTSTRAP-vidofnir.zip", "url": "https://volla.tech/filedump/vollaos/volla-14.0-20250128-stable-BOOTSTRAP-vidofnir.zip", "size": 0},
    ],
    "violet": [
        {"name": "splash.img", "url": "https://gitlab.com/ubports/community-ports/android9/xiaomi-redmi-note-7-pro/xiaomi-violet/-/jobs/artifacts/master/raw/out/splash.img?job=devel-flashable", "size": 0},
        {"name": "recovery.img", "url": "https://gitlab.com/ubports/community-ports/android9/xiaomi-redmi-note-7-pro/xiaomi-violet/-/jobs/artifacts/master/raw/out/recovery.img?job=devel-flashable", "size": 0},
        {"name": "vendor.zip", "url": "https://github.com/ubuntu-touch-violet/ubuntu-touch-violet/releases/download/20210510/vendor.zip", "size": 0},
        {"name": "dtbo.img", "url": "https://github.com/ubuntu-touch-violet/ubuntu-touch-violet/releases/download/20210510/dtbo.img", "size": 0},
        {"name": "dsp.img", "url": "https://github.com/ubuntu-touch-violet/ubuntu-touch-violet/releases/download/20210510/dsp.img", "size": 0},
        {"name": "bluetooth.img", "url": "https://github.com/ubuntu-touch-violet/ubuntu-touch-violet/releases/download/20210510/bluetooth.img", "size": 0},
        {"name": "modem.img", "url": "https://github.com/ubuntu-touch-violet/ubuntu-touch-violet/releases/download/20210510/modem.img", "size": 0},
        {"name": "vbmeta.img", "url": "https://github.com/ubuntu-touch-violet/ubuntu-touch-violet/releases/download/20210510/vbmeta.img", "size": 0},
    ],
    "yggdrasil": [
        {"name": "halium-unlocked-recovery_yggdrasil.img", "url": "https://cdimage.ubports.com/devices/halium-unlocked-recovery_yggdrasil.img", "size": 0},
        {"name": "volla-yggdrasil-9.0-ubports-installer-bootstrap.zip", "url": "https://volla.tech/filedump/volla-yggdrasil-9.0-ubports-installer-bootstrap.zip", "size": 0},
        {"name": "volla-12.1-20240228-stable-BOOTSTRAP-yggdrasil.zip", "url": "https://volla.tech/filedump/vollaos/volla-12.1-20240228-stable-BOOTSTRAP-yggdrasil.zip", "size": 0},
        {"name": "volla-yggdrasil-10.0-ubports-installer-bootstrap.zip", "url": "https://volla.tech/filedump/volla-yggdrasil-10.0-ubports-installer-bootstrap.zip", "size": 0},
        {"name": "volla-yggdrasil-10.0-system.zip", "url": "https://volla.tech/filedump/vollaos/volla-yggdrasil-10.0-system.zip", "size": 0},
        {"name": "image-fastboot-yggdrasil.zip", "url": "https://images.droidian.org/droidian/nightly/arm64/volla/image-fastboot-yggdrasil.zip", "size": 0},
        {"name": "droidian-OFFICIAL_volla_yggdrasil-arm64-cutie-phone-28.zip", "url": "https://github.com/cutie-shell/droidian/releases/download/nightly/droidian-OFFICIAL_volla_yggdrasil-arm64-cutie-phone-28.zip", "size": 0},
    ],
    "yggdrasilx": [
        {"name": "volla-yggdrasilx-10.0-ubports-installer-bootstrap.zip", "url": "https://volla.tech/filedump/volla-yggdrasilx-10.0-ubports-installer-bootstrap.zip", "size": 0},
        {"name": "volla-12.1-20240229-stable-BOOTSTRAP-yggdrasilx.zip", "url": "https://volla.tech/filedump/vollaos/volla-12.1-20240229-stable-BOOTSTRAP-yggdrasilx.zip", "size": 0},
        {"name": "volla-10.1-20211002-SFOS-BOOTSTRAP-yggdrasilx.zip", "url": "https://volla.tech/filedump/vollaos/volla-10.1-20211002-SFOS-BOOTSTRAP-yggdrasilx.zip", "size": 0},
        {"name": "vollaos-10.1-ygdrassilx-preloader.bin", "url": "https://volla.tech/filedump/vollaos-10.1-ygdrassilx-preloader.bin", "size": 0},
    ],
}

DEVICE_FIRMWARE = {
    "FP3": {"boot.img"},
    "FP4": {"boot.img", "dtbo.img", "recovery.img"},
    "FP5": {"boot.img", "vendor_boot.img"},
    "Spacewar": {"boot.img", "vendor_boot.img"},
    "X00TD": {"vendor_X00TD.zip", "recovery_X00TD.img", "firmware_X00TD.zip"},
    "X605": {"boot.img", "recovery.img"},
    "algiz": {"volla-algiz-13.0-ubports-installer-bootstrap.zip", "volla-14.0-20241124-stable-BOOTSTRAP-algiz.zip"},
    "amar_row_lte": {"boot.img", "recovery.img", "dtbo.img", "vbmeta.img"},
    "amar_row_wifi": {"boot.img", "recovery.img", "dtbo.img", "vbmeta.img"},
    "begonia": {"fw_begonia_V12.0.8.0.zip", "vendor.zip", "dtbo.img", "recovery.img", "vbmeta.img"},
    "billie": {"boot.img", "recovery.img", "persist.img", "dtbo.img", "vbmeta.img"},
    "billie2": {"boot.img", "recovery.img", "dtbo.img", "vbmeta.img"},
    "cheeseburger": {"halium-unlocked-recovery_cheeseburger.img"},
    "citrus": {"recovery.img", "dtbo.img", "super.zip", "vbmeta.img"},
    "denniz": {"super.zip", "recovery.img", "dtbo.img", "vbmeta.img"},
    "dumpling": {"halium-unlocked-recovery_dumpling.img"},
    "enchilada": {"boot.img", "vbmeta.img"},
    "hero2lte": {"recovery_hero2lte.img", "boot-reboot-recovery-hero2lte.img"},
    "herolte": {"recovery_herolte.img", "boot-reboot-recovery-herolte.img"},
    "jasmine_sprout": {"boot.img"},
    "jingpad_a1": {"recovery.img", "vendor.img"},
    "lancelot": {"recovery.img", "dtbo.img", "super.zip", "vbmeta.img"},
    "lavender": {"dtbo.img", "recovery.img", "splash.img", "vbmeta.img", "image-fastboot-lavender.zip", "droidian-OFFICIAL_xiaomi_lavender-arm64-cutie-phone-28.zip"},
    "merlin": {"recovery.img", "dtbo.img", "super.zip", "vbmeta.img"},
    "miatoll": {"recovery.img", "dtbo.img", "image-fastboot-miatoll.zip", "droidian-OFFICIAL_xiaomi_miatoll-arm64-cutie-phone-29.zip"},
    "mimameid": {"volla-mimameid-11.0-ubports-installer-bootstrap-v3.zip", "volla-12.1-20240228-stable-BOOTSTRAP-mimameid.zip", "volla-mimameid-12.0-ubports-installer-bootstrap.zip", "twrp-mimameid.img", "image-fastboot-mimameid.zip", "droidian-OFFICIAL_volla_mimameid-arm64-cutie-phone-30.zip"},
    "mimameid_h12": {"volla-mimameid-12.0-ubports-installer-bootstrap.zip", "volla-12.1-20240228-stable-BOOTSTRAP-mimameid.zip"},
    "mimir": {"volla-mimir-13.0-ubports-installer-bootstrap.zip", "volla-14.0-20250130-stable-BOOTSTRAP-mimir.zip"},
    "pro1x": {"recovery.img"},
    "r1": {"super.zip", "boot.img", "vbmeta.img"},
    "sagit": {"vendor.zip", "recovery.img"},
    "sargo": {"boot.img", "dtbo.img", "vbmeta.img", "image-fastboot-sargo.zip", "droidian-OFFICIAL_google_sargo-arm64-cutie-phone-28.zip"},
    "surya": {"recovery.img", "dtbo.img", "super.img", "vendor.img"},
    "vidofnir_esim": {"volla-vidofnir-12.0-ubports-installer-bootstrap-v3.zip", "volla-14.0-20250128-stable-BOOTSTRAP-vidofnir.zip"},
    "violet": {"splash.img", "recovery.img", "vendor.zip", "dtbo.img", "dsp.img", "bluetooth.img", "modem.img", "vbmeta.img"},
    "yggdrasil": {"halium-unlocked-recovery_yggdrasil.img", "volla-yggdrasil-9.0-ubports-installer-bootstrap.zip", "volla-12.1-20240228-stable-BOOTSTRAP-yggdrasil.zip", "volla-yggdrasil-10.0-ubports-installer-bootstrap.zip", "volla-yggdrasil-10.0-system.zip", "image-fastboot-yggdrasil.zip", "droidian-OFFICIAL_volla_yggdrasil-arm64-cutie-phone-28.zip"},
    "yggdrasilx": {"volla-yggdrasilx-10.0-ubports-installer-bootstrap.zip", "volla-12.1-20240229-stable-BOOTSTRAP-yggdrasilx.zip", "volla-10.1-20211002-SFOS-BOOTSTRAP-yggdrasilx.zip", "vollaos-10.1-ygdrassilx-preloader.bin"},
}
